### ISSUE TITLE
'Tickler' Component Needs To Have Parentheses In Order To Return Valid JSX In The Return Statement

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-event-handling#2] opened 2022-06-28 22:24 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172330?module_item_id=376318

### Concern

The 'Tickler' component does not return JSX properly, as it does not have valid parentheses in the return statement present:

```
function Tickler() {
  function tickle(event) {
    console.log(event);
  }

  return <button onClick={tickle}>Tickle me!</button>;
}
```

### Suggested Changes

This needs to have valid parentheses so that JSX is returned successfully:
```
function Tickler() {
  function tickle(event) {
    console.log(event);
  }

  return (
<button onClick={tickle}>Tickle me!</button>;
)
}
```

**Comment by lizbur10** [comment] 2022-07-01 18:25
Hi @SamuelBanya ! I am not able to reproduce this problem - the Tickle me! button is present when I spin up the app. Recall that when the return statement is a single line of code, it is not necessary to wrap it in parentheses.

I'm going to go ahead and close this issue, but if you still believe there is something wrong with the code, feel free to reopen it.

**Closed as completed by lizbur10** 2022-07-01 18:25 UTC
Labels: se curriculum
